---
- name: Update Cache #equivalente a apt update
  apt:
    update_cache: yes

- name: Install nginx #equivalente a apt install nginx
  apt:
    name: nginx

- name: Instalando pacotes essenciais #Instalando pacotes usuando apt
  apt:
    name:
      - vim
      - curl
      - telnet
      - unzip
      - wget
      - net-tools
      - htop
      - nmap
    state: present

- name: Adicionar usuario #Criando usuario 
  user: 
    name: aquiles
    shell: /bin/bash  

- name: Set a hostname
  ansible.builtin.hostname:
    name: aquiles

- name: copy index.html #copia arquivo html
  copy:
    src: site.html
    dest: /var/www/html  